### ISSUE TITLE
Unable to change nature of Pokemon

### ISSUE THREAD

**Issue by LousyCompany** [codemonkey85/PKMDS-Blazor#15]
I am unable to change any of the nature's of my pokemon heart gold save, everything else works great.

The list of nature's appears but when selecting one it does not update the field. I've tried this on multiple devices but no change.

**Comment by codemonkey85** [comment]
Thanks, I will look into this.

**Comment by codemonkey85** [comment]
Note to self: was able to replicate this issue.
