### ISSUE TITLE
Pokemon Types shown are off

### ISSUE THREAD

**Issue by SamsTheNerd** [codemonkey85/PKMDS-Blazor#18]
<img width="1219" alt="image" src="https://github.com/codemonkey85/PKMDS-Blazor/assets/18472542/7172e7e0-03f0-4426-b89f-3462f4aa2beb">
types seem to be slightly off. Seems consistent, so all electric types get shown as fighting, fairy as bug, etc.

Also the sprites for pikachu forms are off - they all have hats rather than the "rock star" and "cosplay" forms that are listed on the drop down.

**Comment by codemonkey85** [comment]
Thanks, I will look into this.

**Comment by codemonkey85** [comment]
@SamsTheNerd For the types - I can't seem to reproduce this. Can you tell me the steps you take to see this issue? It might help if you attach your save file as well (you can zip it and attach it to a comment in this thread).

For the formes - I think I know the issue here, looking at a fix.

**Comment by SamsTheNerd** [comment]
here's the save file, it's a pokemon X save from the very beginning of the game with the hair color changed: [xproperhair.zip](https://github.com/codemonkey85/PKMDS-Blazor/files/14485742/xproperhair.zip)

https://github.com/codemonkey85/PKMDS-Blazor/assets/18472542/f849510a-a775-435f-ae99-9541cc56d52c

just tried it with a few other save files and it seems like it's specifically when making a new pokemon and not just editing an existing one. Also it looks like a lot of information is missing when you make a new pokemon vs edit an existing one, atleast on the main screen, like the PID, nature, ability, language, and friendship fields, also the cured, egg, infected, and shiny, checkmarks (also it doesn't seem like the shiny checkmark button works or is even clickable), not sure if that stuff is related ?

**Comment by codemonkey85** [comment]
@SamsTheNerd Ah, thanks for the info. Yeah, creating a new Pokémon is a process that needs some work.

**Comment by codemonkey85** [comment]
Linking to #24.

**Comment by codemonkey85** [comment]
At some point I fixed this by setting a default game of origin on a blank slot.
