### ISSUE TITLE
Hard to select held items

### ISSUE THREAD

**Issue by SamsTheNerd** [codemonkey85/PKMDS-Blazor#19]
Clicking on a pokemon and trying to give them a held item, the input box keeps replacing my text with "(None)", making it difficult to select an item. Clicking on and off the pokemon a few times seems to help it ?

**Comment by codemonkey85** [comment]
Weird. I will look into this.

**Comment by codemonkey85** [comment]
@SamsTheNerd I can't seem to reproduce this. Can you tell me the steps you take to see this issue? It might help if you attach your save file as well (you can zip it and attach it to a comment in this thread).
![image](https://github.com/codemonkey85/PKMDS-Blazor/assets/1414036/40feaff4-2830-4fe9-99c4-3a861b03149e)

**Comment by codemonkey85** [comment]
I think I've seen this issue happen specifically in mobile view. Will attach screenshots when I get a chance.

**Comment by codemonkey85** [comment]
Tried reproducing this today and it seems to be fixed.
