### ISSUE TITLE
Feature Request -- pokemon showdown format export 

### ISSUE THREAD

**Issue by Tmorg25** [codemonkey85/PKMDS-Blazor#20]
Wondering if there's an easy way to add a button to export current party to pokemon showdown format -- I use pkhex a lot to easily get party info to calc battles in romhacks and challenge nuzlockes and being able to quickly import a sav and get my party info in showdown would be sweet

**Comment by codemonkey85** [comment]
Great idea! I believe PKHeX does this as well, so I should be able to check their implementation.

**Comment by Tmorg25** [comment]
👍 if you don't have the time in the immediate future let me know! I've been looking for something to do in my free time and can explore as well, it'll give me an excuse to learn some csharp

**Comment by codemonkey85** [comment]
Give it a shot if you want to. I might have some time this weekend, but I have some bugs that need work as well.
