### ISSUE TITLE
Pokemon Run and Bun sav file not uploading pokemon correctly

### ISSUE THREAD

**Issue by samostrom** [codemonkey85/PKMDS-Blazor#21]
Seems like when I upload my pokemon run and bun rom hack, it doesn't work for the pokemon. It's disappointing because for us Mac users, this is a god send. 

Here's some screenshots!
<img width="1039" alt="Screen Shot 2024-03-23 at 11 05 36 AM" src="https://github.com/codemonkey85/PKMDS-Blazor/assets/68084007/1d81c5b2-9dea-47eb-b9d7-392c5e4bb778">
<img width="1239" alt="Screen Shot 2024-03-23 at 11 05 51 AM" src="https://github.com/codemonkey85/PKMDS-Blazor/assets/68084007/bdc71e53-f109-4fbe-8466-1d70b794d4cb">

**Comment by codemonkey85** [comment]
This app does not support ROM hacks - the rule is basically if PKHeX doesn’t support it, neither do I.
