### ISSUE TITLE
Shiny button is not working for pokemon sword 

### ISSUE THREAD

**Issue by AnoopMukthi** [codemonkey85/PKMDS-Blazor#22]
Hello,
When I hover the cursor on Shiny button, it's cursor doesn't change to hand and also it's not getting clicked.please do fix this bug.
Game : Pokemon Sword

**Comment by codemonkey85** [comment]
This isn't a bug - the shiny checkbox is read-only. It's just there (for now) to show you if the Pokémon is shiny or not.
