### ISSUE TITLE
Nothing happens when opening the website

### ISSUE THREAD

**Issue by m0shmall0w** [codemonkey85/PKMDS-Blazor#30]
I'm currently using a Google Pixel 8 Pro and I'm trying to use the site, the site will open and load. However once finished loading, it will look like the following picture, and when I press of the various parts of the site, namely the 3 lines for the menu, and the "Please load a save file" areas; nothing happens.

![Screenshot_20240602-182350.png](https://github.com/codemonkey85/PKMDS-Blazor/assets/66012741/a5090590-5c95-413b-ba8b-7d6dcfca57dd)

**Comment by codemonkey85** [comment]
It seems to be working for me. Maybe your network connection wasn't good? Can you try again?

https://github.com/codemonkey85/PKMDS-Blazor/assets/1414036/a1adfeb1-1168-4c45-9898-062a8345e59e

**Comment by idkmanwtt** [comment]
Also have this issue on iOS 14.6 it just doesn’t do anything nothing is clickable

**Comment by codemonkey85** [comment]
@idkmanwtt As far as I know iOS 14.6 should be supported (both server-based and WASM). I'm not sure where your issue is coming from. Have you tried refreshing?

**Comment by idkmanwtt** [comment]
Yeah I tried everything, even tried different browsers but none worked. Tried refreshing tried requesting desktop site, cleared cookies and went into a private tab. Nothing :(

**Comment by codemonkey85** [comment]
@idkmanwtt I realize it's been a while, but FYI, I think I fixed this issue - looks like it may be a compatibility issue with older versions of Safari (<16). Long story short, I disabled a feature used by the framework, and now older browsers should work.
