### ISSUE TITLE
Impossible to put pokemons on shiny.

### ISSUE THREAD

**Issue by GenieManager422** [codemonkey85/PKMDS-Blazor#33]
Hello,

It is currently impossible to put pokemon on « shiny » using the mobile interface.

**Comment by codemonkey85** [comment]
It's impossible on the desktop interface as well. That button is read-only at the moment - to show you that it is or isn't shiny. This is a feature I have yet to work on.

**Comment by GenieManager422** [comment]
Thank you for your answer.

I hope this feature will be added soon :)
