### ISSUE TITLE
The Pokémon that I transfer are automatically shiny 

### ISSUE THREAD

**Issue by Wawa24052008** [codemonkey85/PKMDS-Blazor#34]
When I transfer a Pokémon in Pokémon x (on my emulator folium) the Pokémon is automatically shiny but I don’t want it to be. Is that a solution for this issue please I’m stuck.

**Comment by codemonkey85** [comment]
I need more information. Where are you transferring this Pokémon to and from? Can you provide a sample save file and Pokémon file?

**Comment by Wawa24052008** [comment]
I transfer the Pokémon from PKMDS to Pokémon x in the emulator folium
![IMG_8119](https://github.com/user-attachments/assets/0d0a1556-b260-44d8-bdee-8c4645826a9f)
![IMG_8120](https://github.com/user-attachments/assets/78c5bfac-64fd-415d-abb1-acd5d1338293)
In those pictures figure a victim I that I generated in PKMDS and I revive it automatically shiny, same for diancie,hoopa and volcanism.

**Comment by codemonkey85** [comment]
With a PID of 0 for each? I think you're making them shiny yourself, without realizing it. https://bulbapedia.bulbagarden.net/wiki/Shiny_Pok%C3%A9mon#Generation_VI
