### ISSUE TITLE
Doesnt correctly load saves for custom ROMs

### ISSUE THREAD

**Issue by EthanLawr** [codemonkey85/PKMDS-Blazor#35]
When loading a Pokemon Unbound save file it will load your name, gender, playtime, and first pokemon in your party correctly. All other data will not be correct or missing. Below is the result.

![image](https://github.com/user-attachments/assets/47e5c3e2-4f1c-46d0-9292-ec6da0378631)

Whats expected is there to be a full party and box of pokemon. Instead only the first pokemon of the party shows up.

Pokemon Unbound (v2.1.1.1) appears to be a custom ROM specific issue. After looking into the issue I found that UltraViolet (another custom ROM) loaded fine. Below we can see this to be true.

![image](https://github.com/user-attachments/assets/80fff744-17b2-4bec-95a4-1164a005b08c)

Any level of a fix would be highly appreciated. These save files were exported using the Delta (v1.6s) IOS application with the GBA emulator it provides.

**Comment by codemonkey85** [comment]
PKMDS does not, and will never, support custom ROMs. The app is powered by [PKHeX.Core, created and maintained by Kaphotics for the use of the Windows app PKHeX](https://github.com/kwsch/PKHeX). Basically this app supports the same things that app supports. Sorry!
