### ISSUE TITLE
Edit save not importing to game

### ISSUE THREAD

**Issue by TyFuzer** [codemonkey85/PKMDS-Blazor#38]
Hello I’m using delta on iOS playing Pokemon emerald and I’ve tried editing my Pokemon save went to load save file opend made alterations and saved it and then went to import it went to open game and the changes hadn’t saved so they are not goin through need help idk if im doing it wrong or it’s bugged

**Comment by codemonkey85** [comment]
I see you closed this. Just curious, what was the issue in the end?
