### ISSUE TITLE
(Suggestion/Enhancement) Add Event Injector

### ISSUE THREAD

**Issue by BuffYoda21** [codemonkey85/PKMDS-Blazor#43]
Could you make a way to import wondercards via .pgf files like you can in PKHeX?

**Comment by codemonkey85** [comment]
Good question. I'll check out the PKHeX API and see if there's a simple way to do this. (I expect there is.)

**Comment by codemonkey85** [comment]
For now, I've added a Mystery Gift database browser / injector.
