### ISSUE TITLE
Web App won’t allow ability changes

### ISSUE THREAD

**Issue by znhernand** [codemonkey85/PKMDS-Blazor#46]
Decided to test this out with a throwaway file. Loaded a Pokémon Ruby save and tried to change the ability of a Seedot I caught from Early Bird to Chlorophyll but the app acts as if Early Bird is the only ability available to Seedot. Even if I clear the ability field entirely and type out the full ability name, the second I click off of the field, it reverts to the original ability. Tested with FireRed and HeartGold on some other Pokémon that have 2 ability options and got the same result.

**Comment by codemonkey85** [comment]
@znhernand This has been fixed. Thanks for bringing it to my attention.

**Comment by znhernand** [comment]
No problem.
