### ISSUE TITLE
Gen 1 and 2 EV issues

### ISSUE THREAD

**Issue by Evilstar006** [codemonkey85/PKMDS-Blazor#48]
The limit on RBY, and likely GSC, EVs is capped at 255, which would not be an immediate issue if it was taking both bit values into account at once but instead it is only changing one but leaving the final value closer to a max of 15 EVs so either both values need to change simultaneously or the cap raised to 65535 for early games that use the old stat system.

**Comment by Evilstar006** [comment]
The problem could be solved by squaring the EV values that way when it's imported into Smogon it doesn't have an issue.

**Comment by Evilstar006** [comment]
The issue is still there for Red and Blue unfortunately, EX Bulbasaur with max stats in HP should equal 293, but with the current programming limits it still won't go above 234.

**Comment by codemonkey85** [comment]
@Evilstar006 I'm seeing the full 293 in my testing. Can you check again?
![image](https://github.com/user-attachments/assets/0d5644eb-b09b-47af-98c0-b6d07ce359fd)

**Comment by Evilstar006** [comment]
Yeah for some reason it still resets it back down to 255 on my end, I even tried to make a new instance of the Pokémon see if that fixed the issue.

![Screenshot_20241025_102422](https://github.com/user-attachments/assets/3e5ba9cf-7931-4456-9e07-4d2da16c0851)

**Comment by codemonkey85** [comment]
I was going to suggest clearing cache / site data for the app. Not sure why it would behave differently on desktop vs mobile view.

**Comment by Evilstar006** [comment]
I can maybe try that and maybe that has something to do with it as perhaps it clears the site data automatically to load the desktop or mobile version, honestly I wouldn't have thought about it at all if I hadn't realized you were doing the edits on desktop and decided to humor the idea of switching.

**Comment by Evilstar006** [comment]
I'm guessing that's exactly what it is because it works fine on mobile view now.

**Comment by codemonkey85** [comment]
Right, the app should behave the same way regardless of how you view it, but unfortunately I seem to have no control over how or when the browser decides to redownload the app and / or its assets. So as I push out updates I'm kind of at the mercy of those things as to whether or not users see said updates.

**Comment by Evilstar006** [comment]
The important thing is you have a known issue and a possible solution to that issue if it ever arises again, keep up the good work.
