### ISSUE TITLE
EV Maximums 

### ISSUE THREAD

**Issue by znhernand** [codemonkey85/PKMDS-Blazor#51]
A small bug, EVs are supposed to cap off at a maximum of 252 not 255.

**Comment by Evilstar006** [comment]
Not necessarily a bug, EVs can go up to 255, although stat changes only happen every 4 points so it's not necessary for them to go up to 255 as you'd just be wasting EVs doing nothing.

**Comment by codemonkey85** [comment]
Technically this is a bug for Gen VI and onward, as EVs should cap at 252 in those games. I'll keep it open for now.

**Comment by Evilstar006** [comment]
I guess you're right actually, although it looks like that's a change from Gen 7 onward, which means I wasted time trying to get my stats perfect in SwSh.

**Comment by codemonkey85** [comment]
@Evilstar006 It's Gen VI onward: https://bulbapedia.bulbagarden.net/wiki/Effort_values#Generation_VI

> individual stats now max out at 252 EVs instead of 255; if a Pokémon is transferred forward into a Generation VI game while it has 253 or more effort values in a stat, they will be reduced to 252

**Comment by Evilstar006** [comment]
It's still a nice quality of life that I wasn't aware of to much gen 3 and 4 for me, although it would be a nice quality of life feature for Gens 3 through I guess 5 lol although you'd probably have to put the same handler in. If I knew more on the programming language you were using I'd help, but I enjoy some more niche languages, but I'm excited to see what will become of this, it's very handy right now with my computer Out of Commission.

**Comment by codemonkey85** [comment]
This is now being worked on.
