### ISSUE TITLE
PID Hex Format

### ISSUE THREAD

**Issue by codemonkey85** [codemonkey85/PKMDS-Blazor#58]
> Hey if that's really you I have a question to ask, how come on Pkmds the PID is all numbers?
For example both on PKHex and Pokefinder the PID of my Breloom is BF693437 meanwhile on your site it shows as 3211342903 and I don't know how to convert it, the same goes for every other pokemon.

https://www.reddit.com/r/EmulationOniOS/comments/1e3gwud/comment/lv67hbx/

**Comment by BuffYoda21** [comment]
Though it would be nice for it to display in Hexadecimal like on PKHeX it is a pretty easy conversion. You can find Decimal to Hex converters online pretty easily that will do the job for the time being. (Or you can do it by hand if you really wanted)
