### ISSUE TITLE
Incorrect Met location for Pokemon transferred from Colo/XD

### ISSUE THREAD

**Issue by jbenper** [codemonkey85/PKMDS-Blazor#70]
<img width="777" alt="Screenshot 2024-12-04 at 1 15 02 PM" src="https://github.com/user-attachments/assets/69a2c844-bcf4-4a08-9b4b-1c120aa9bba4">

See picture for example, but it seems that Pokemon transferred from Colo/XD have the correct origin game, but the Met Location is incorrect.

**Comment by codemonkey85** [comment]
How did you do the transfer exactly? And what game did you transfer the Pokémon into?

**Comment by codemonkey85** [comment]
In that case the met location should be "link trade". Can you please share a copy of the save file so I can take a peek? You may have to zip it to attach it to a comment on this issue.

**Comment by jbenper** [comment]
[Emerald.sav.zip](https://github.com/user-attachments/files/18053783/Emerald.sav.zip)
Here is the sav. The first row of box 1 for sure was traded with the normal gamecube-gameboy link. My Colo file got corrupted while trading, so I restored a backup save and then used pkhex to transfer the rest of Box 1 and Box 2

**Comment by codemonkey85** [comment]
Ahh, I think I see what's going on here now. It's simply a matter of having the correct location list in the location search box. PKHeX does something here to switch it out depending on certain factors (like the origin game). I'll work on a fix for this and report back when it's ready.

**Comment by codemonkey85** [comment]
@jbenper This issue has been addressed. Thank you for bringing it to my attention!
![image](https://github.com/user-attachments/assets/37c3a11b-616c-450c-aa02-6bae120e02b1)

**Comment by jbenper** [comment]
Thank you! And thank you for making a web version, has been super nice to use.

**Comment by codemonkey85** [comment]
Just out of curiosity, if you have access to PKHeX, why do you use PKMDS?

**Comment by jbenper** [comment]
I have a Mac, so my access to pkhex is through a virtual machine. Which is kind of annoying to spin up just for pkhex. And I dont feel like bothering with Wine. PKMDS is way easier to just open real quick and spot check some things. I have mainly been using it to double check EVs.
